accounts/urls.py
from django.urls import path

from .views import (
    LogInView, SignUpView,LogOutView,linkedin_lix,linkedin_group,linkedin_search,facebook,twitter,accelerators,twitter_web3,Blank,wonderverse,scaleups,founders,data_scientist_phantom,nft_phantom,defi_phantom,dapp_phantom,dao_phantom,yf_phantom,data_scientist_lix,nft_lix,defi_lix,dapp_lix,dao_lix,yf_lix,entrepreneurs,cm_phantom,cb_phantom,cmanag_phantom,dc_phantom,cm_lix,cb_lix,cmanag_lix,dc_lix,entrepreneurs_phantom,founders_phantom,digital_marketing,blockchain,data_analysis,venture_funding,uiux,pm_lix,blockchain_phantom,digital_marketing_phantom,data_analysis_phantom,venture_funding_phantom,uiux_phantom,pm_phantom,cb_twi_view,cg_twi_view,cm_twi_view,twi_marketing_view,web3_com_twi_view,web3_marketing_twi_view,discordbot_twi_view,chatbots_twi_view,vc_lix,angel_lix,sc_lix,fr_lix,pi_lix,vc_phantom,angel_phantom,sc_phantom,fr_phantom,pi_phantom,vc_fb,ai_fb,pd_fb,pi_fb,ba_fb,vc_twi,angeli_twi,sc_twi,wf_twi,wg_twi,fr_twi,wp_twi,pd_twi,pi_twi,ba_twi,wi_twi,design_twi,gd_twi,vd_twi,md_twi,bc_twi,d3_fb,gd_fb,d3_design_lix,gd_lix,vd_lix,md_lix,bc_lix,d3_phantom,gd_phantom,vd_phantom,md_phantom,bc_phantom,ai_phantom,ml_phantom,algo_phantom,dm_phantom,ann_phantom,dp_phantom,ai_lix,ml_lix,algo_lix,dm_lix,ann_lix,dp_lix,angle_investor_fb_view,ml_fb,algo_fb,dm_fb,ann_fb,ai_twi,ml_twi,algo_twi,dm_twi,ann_twi,dp_twi,dmarketing_fb,block_fb,sd_fb,da_fb,ux_ui_fb,enter_fb,uiux_instagram,enter_instagram,dm_instagram,dmar_twi,enter_twi,uxuidesign_twi,figma_lix,notion_lix,slack_lix,trello_lix,miro_lix,micromenter_insta,menterpass_insta,figma_twi,onalytica_twi,slack_twi,trello_twi,miro_twi,notion_twi
        ,micromenter_twi,
        menterpass_twi,figma_phantom,notion_phantom,slack_phantom,trello_phantom,bd_design_lix,bd_design_phantom,mobile_dev_phantom,mobile_dev_lix,Web_dev,web_dev_phantom_display,software_dev_phantom,

        algo_fb_ads,ai_fb_ads,dataanalysis_fb_ads,dm_fb_ads,ml_fb_ads,ann_fb_ads,algo_lix_ads,ai_lix_ads,dataanalysis_lix_ads,dm_lix_ads,dp_lix_ads,ds_lix_ads,ml_lix_ads,ann_lix_ads,algo_phantom_ads,ai_phantom_ads,dataanalysis_phantom_ads,dm_phantom_ads,dp_phantom_ads,ds_phantom_ads,ml_phantom_ads,ann_phantom_ads,algo_twi_ads,ai_twi_ads,dm_twi_ads,dp_twi_ads,ml_twi_ads,ann_twi_ads,

        figma_lix_ads,notion_lix_ads,slack_lix_ads,trello_lix_ads,figma_phantom_ads,notion_phantom_ads,slack_phantom_ads,trello_phantom_ads,figma_twi_ads,miro_twi_ads,notion_twi_ads,onalytica_twi_ads,slack_twi_ads,trello_twi_ads,

        cb_lix_ads,cmanag_lix_ads,cm_lix_ads,dc_lix_ads,cb_phantom_ads,cmanag_phantom_ads,cm_phantom_ads,dc_phantom_ads,chatbot_twi_ads,cb_twi_ads,cg_twi_ads,cm_twi_ads,db_twi_ads,twi_marketing_twi_ads,web3_commu_twi_ads,web3_marketing_twi_ads,

        enterpreneurs_fb_ads,enterpreneurs_lix__ads,founder_lix_ads,enterpreneurs_phantom_ads,founders_phantom_ads,enterpreneurs_twi_ads,

        d3_design_fb_ads,graphic_design_fb_ads,uiux_design_fb_ads,d3_design_lix_ads,brand_designers_lix_ads,branding_consultant_lix_ads,graphic_design_lix_ads,marketing_designer_lix_ads,uiux_lix_ads,visual_design_lix_ads,d3_design_phantom_ads,brand_designers_phantom_ads,branding_consultant_phantom_ads,graphic_design_phantom_ads,marketing_designer_phantom_ads,uiux_design_phantom_ads,visual_design_phantom_ads,d3_design_twi_ads,branding_consultant_twi_ads,graphic_design_twi_ads,marketing_designer_twi_ads,uiux_design_twi_ads,visual_design_twi_ads,

        micromentor_twi_ads,mentorpass_twi_ads,display_count,software,

        digital_marketing_fb_ads,digital_marketing_lix_ads,digital_marketing_phantom_ads,digital_marketing_twi_ads,
        pm_fit_lix_ads,pm_fit_phantom_ads,
        software_development_fb_ads,mobile_development_lix_ads,software_development_lix_ads,web_development_lix_ads,mobile_development_phantom_ads,software_development_phantom_ads,web_development_phantom_ads,

        angle_investor_fb_ads,business_angle_fb_ads,pitchdesk_fb_ads,private_investor_fb_ads,venture_capital_fb_ads,angle_investor_lix_ads,fundraising_lix_ads,private_investor_lix_ads,seed_capital_lix_ads,venture_capital_lix_ads,angle_investor_phantom_ads,fundraising_phantom_ads,private_investor_phantom_ads,seed_capital_phantom_ads,venture_capital_phantom_ads,angle_investor_twi_ads,business_angle_twi_ads,fundraising_twi_ads,pitchdesk_twi_ads,private_investor_twi_ads,seed_capital_twi_ads,venture_capital_twi_ads,web3_fund_twi_ads,web3_grants_twi_ads,web3_investor_twi_ads,whitepaper_twi_ads,
        blockchain_fb_ads,blockchain_lix_ads,dao_lix_ads,dapp_lix_ads,defi_lix_ads,nft_lix_ads,yield_farming_lix_ads,blockchain_phantom_ads,dao_phantom_ads,dapp_phantom_ads,defi_phantom_ads,nft_phantom_ads,yield_farming_phantom_ads,defi_twi,defi_twi_ads,

        entrepreneurs_insta_ads,digital_marketing_insta_ads,uiux_insta_ads,micromente_insta_ads,menterpass_insta_ads,graph_list
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('graph_list/', graph_list, name='graph_list'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
   
    path('defi_twi/',defi_twi,name='defi_twi'),
    path('defi_twi_ads/',defi_twi_ads,name='defi_twi_ads'),

    
    path('figma_lix/',figma_lix,name='figma_lix'),
    path('notion_lix/',notion_lix,name='notion_lix'),
    path('slack_lix/',slack_lix,name='slack_lix'),
    path('trello_lix/',trello_lix,name='trello_lix'),
    path('miro_lix/',miro_lix,name='miro_lix'),
    path('micromenter_insta/',micromenter_insta,name='micromenter_insta'),
    path('menterpass_insta/',menterpass_insta,name='menterpass_insta'),
    path('micromenter_twi/',micromenter_twi,name='micromenter_twi'),
    path('menterpass_twi/',menterpass_twi,name='menterpass_twi'),

    path('figma_twi/',figma_twi,name='figma_twi'),
    path('onalytica_twi/',onalytica_twi,name='onalytica_twi'),
    path('slack_twi/',slack_twi,name='slack_twi'),
    path('trello_twi/',trello_twi,name='trello_twi'),
    path('miro_twi/',miro_twi,name='miro_twi'),
    path('notion_twi/',notion_twi,name='notion_twi'),

    path('figma_phantom/',figma_phantom,name='figma_phantom'),
    path('notion_phantom/',notion_phantom,name='notion_phantom'),
    path('slack_phantom/',slack_phantom,name='slack_phantom'),
    path('trello_phantom/',trello_phantom,name='trello_phantom'),
    path('bd_design_lix/',bd_design_lix,name='bd_design_lix'),
    path('bd_design_phantom/',bd_design_phantom,name='bd_design_phantom'),

    path('linkedin_lix/',linkedin_lix,name='linkedin_lix'),
    path('venture_capital_lix/',vc_lix,name='venture_capital_lix'),
    path('angle_investor_lix/',angel_lix,name='angle_investor_lix'),
    path('private_investor_lix/',pi_lix,name='private_investor_lix'),
    path('seed_capital_lix/',sc_lix,name='seed_capital_lix'),
    path('fundraising_lix/',fr_lix,name='fundraising_lix'),
    path('venture_capital_phantom/',vc_phantom,name='venture_capital_phantom'),
    path('angle_investor_phantom/',angel_phantom,name='angle_investor_phantom'),
    path('seed_capital_phantom/',sc_phantom,name='seed_capital_phantom'),
    path('fundraising_phantom/',fr_phantom,name='fundraising_phantom'),
    path('private_investor_phantom/',pi_phantom,name='private_investor_phantom'),

    path('venture_capital_fb/',vc_fb,name='venture_capital_fb'),
    path('angle_investor_fb/',angle_investor_fb_view,name='angle_investor_fb'),
    path('pitchdesk_fb/',pd_fb,name='pitchdesk_fb'),
    path('private_investor_fb/',pi_fb,name='private_investor_fb'),
    path('business_angle_fb/',ba_fb,name='business_angle_fb'),


    path('venture_capital_twi/',vc_twi,name='venture_capital_twi'),
    path('angle_investor_twi/',angeli_twi,name='angle_investor_twi'),
    path('seed_capital_twi/',sc_twi,name='seed_capital_twi'),
    path('web3_fund_twi/',wf_twi,name='web3_fund_twi'),
    path('web3_grants_twi/',wg_twi,name='web3_grants_twi'),
    path('fundraising_twi/',fr_twi,name='fundraising_twi'),
    path('whitepaper_twi/',wp_twi,name='whitepaper_twi'),
    path('pitchdesk_twi/',pd_twi,name='pitchdesk_twi'),
    path('private_investor_twi/',pi_twi,name='private_investor_twi'),
    path('business_angle_twi/',ba_twi,name='business_angle_twi'),
    path('web3_investor_twi/',wi_twi,name='web3_investor_twi'),

    path('digital_marketing_fb/',dmarketing_fb,name='digital_marketing_fb'),
    path('block_fb/',block_fb,name='block_fb'),
    path('sd_fb/',sd_fb,name='sd_fb'),
    path('da_fb/',da_fb,name='da_fb'),
    path('ux_ui_fb/',ux_ui_fb,name='ux_ui_fb'),
    path('enter_fb/',enter_fb,name='enter_fb'),
    path('uiux_instagram/',uiux_instagram,name='uiux_instagram'),
    path('enter_instagram/',enter_instagram,name='enter_instagram'),
    path('dm_instagram/',dm_instagram,name='dm_instagram'),
    path('dmar_twi/',dmar_twi,name='dmar_twi'),
    path('enter_twi/',enter_twi,name='enter_twi'),
    path('uxuidesign_twi/',uxuidesign_twi,name='uxuidesign_twi'),

    path('3d_design_lix/',d3_design_lix,name='3d_design_lix'),
    path('graphic_design_lix/',gd_lix,name='graphic_design_lix'),
    path('visual_design_lix/',vd_lix,name='visual_design_lix'),
    path('marketing_designer_lix/',md_lix,name='marketing_designer_lix'),
    path('branding_consultant_lix/',bc_lix,name='branding_consultant_lix'),


    path('3d_design_phantom/',d3_phantom,name='3d_design_phantom'),
    path('graphic_design_phantom/',gd_phantom,name='graphic_design_phantom'),
    path('visual_design_phantom/',vd_phantom,name='visual_design_phantom'),
    path('marketing_designer_phantom/',md_phantom,name='marketing_designer_phantom'),
    path('branding_consultant_phantom/',bc_phantom,name='branding_consultant_phantom'),

    path('3d_design_twi/',design_twi,name='3d_design_twi'),
    path('graphic_design_twi/',gd_twi,name='graphic_design_twi'),
    path('visual_design_twi/',vd_twi,name='visual_design_twi'),
    path('marketing_designer_twi/',md_twi,name='marketing_designer_twi'),

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
   

    path('accounts/', include('accounts.urls')),
    
    #path('display_data/',include('display_data.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views/login.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaUsernameForm, SignInViaEmailOrUsernameForm, SignUpForm,
)
from .models import Activation,Instagram_talk,Linkedin_lix_talk,Linkedin_group_talk,Linkedin_search_talk,Facebook_talk,Accelerators_talk_new,blank,Wonderverse,Twitter_talk_web3,Twitter_talk_web2,Entrepreneur1,Founder1,Scaleup1,Web_dev_lix,Web_dev_phantom
import sqlite3
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import csv, io
import pandas as pd
from datetime import datetime
from pathlib import Path
import os
from django.http import HttpResponse
from django.db.models import Q

class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/log_in.html'

    @staticmethod
    def get_form_class(**kwargs):
        #if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
         #   return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
      

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('You are signed up. To activate the account, follow the link sent to the mail.'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('You are successfully signed up!'))

        return redirect('index')



class LogOutView(LoginRequiredMixin, BaseLogoutView):
    template_name = 'accounts/log_out.html'

accounts/templates/accounts/display1.html
<html>
   
    <body>
           
            <table id="albums" class="table table-bordered">
                <thead>
                    <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Mobile</th>
                  
                    </tr>
                </thead>
                <tbody>
                    {% for emp_list in emp %}
                    <tr>
                    <td>{{ emp_list.fullName }}</td>
                    <td>{{ emp_list.profileUrl }}</td>
                    <td>{{ emp_list.query }}</td>
                    
                    </tr>
                    {% endfor %}
                </tbody>
            </table> 
       
    </body>
</html>

accounts/templates/accounts/graph.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% if request.user.is_authenticated %}

        <!--{% trans 'Your username is' %} <b>{{ request.user.username }}</b>-->
       
<p><b style="font-size: 150%">The Spaced Data Graphs </b></b></p>
        
<table  style="border-spacing: 500px" >



<tr><td style="margin-bottom: 10px;padding-right: 10px;" ><b><u><h6 style="color:black;">Head Category and Subcategory</h6></u></b></td></tr>
<tr><td><a href="https://chaitali1006.github.io/spaced-category-visulization/">Head Category and Subcategory</a>
<td></td><td></td>      

<tr style="visibility: hidden"><td>a </td><td> a</td></tr>
<tr><td style="margin-bottom: 10px;padding-right: 10px;" ><b><u><h6 style="color:black;">LinkedIn Data Graphs</h6></u></b></td></tr>

<tr><td><a href="https://chaitali1006.github.io/spaced-linkdln-visulization/">LinkedIn Graph with Location Count</a></td>


</tr>
<tr><td><a href="https://chaitali1006.github.io/spaced-linkdln-graph-with-name-only/">LinkedIn Graph with Full Name</a></td>
<td></td><td></td>
<td></td>

<tr style="visibility: hidden"><td>a </td><td> a</td></tr>

<tr><td style="margin-bottom: 10px;padding-right: 10px;" ><b><u><h6 style="color:black;">Facebook Data Graphs</h6></u></b></td></tr>

<tr><td><a href="https://chaitali1006.github.io/spaced-facebook-fullname/">Facebook Graph with Full Name</a></td>

<td></td>
<tr style="visibility: hidden"><td>a </td><td> a</td></tr>
<tr><td style="margin-bottom: 10px;padding-right: 10px;" ><b><u><h6 style="color:black;">Instagram Data Graphs</h6></u></b></td></tr>

<tr><td><a href="https://chaitali1006.github.io/spaced-instagram-username/">Instagram Graph with User Name</a></td>

<td></td>

<tr style="visibility: hidden"><td>a </td><td> a</td></tr>

<tr><td style="margin-bottom: 10px;padding-right: 10px;" ><b><u><h6 style="color:black;">Twitter Head Category Data Graphs</h6></u></b></td></tr>

<tr><td><a href="https://chaitali1006.github.io/spaced_AI_twitter/">AI/ Machine Learning Graph with User Name</a></td>

<td></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_collaboration_tools_twitter/">Collaboration Tools Graph with User Name</a></td>

<td></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_community_buiilding_twitter/">Community Building Graph with User Name</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_design_twitter/">Design Graph with User Name</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_expert_networks_twitter/">Expert Network Graph with User Name</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_venture_funding_twitter/">Venture Funding Graph with User Name</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_AI_twitter_location/">AI/ Machine Learning Graph with Location</a></td>

<td></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_collaboration_tools_twitter_location/">Collaboration Tools Graph with Location</a></td>

<td></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_community_buiilding_twitter_location/">Community Building Graph with Location</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_design_twitter_location/">Design Graph with Location</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_expert_networks_twitter_location/">Expert Network Graph with Location</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_venture_funding_twitter_location/">Venture Funding Graph with Location</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_AI_twitter_followers/">AI/ Machine Learning Graph with Followers Count</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_collaboration_tools_twitter_followers/">Collaboration Tools Graph with Followers Count</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_community_buiilding_twitter_followers/">Community Building Graph with Followers Count</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_design_twitter_followers/">Design Graph with Followers Count</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_expert_networks_twitter_followers/">Expert Network Graph with Followers Count</a></td>

<tr><td><a href="https://chaitali1006.github.io/spaced_venture_funding_twitter_followers/">Venture Funding Graph with Followers Count</a></td>




<td></td>



<!-- <tr><td><a href="https://spaced-data-center.herokuapp.com/accounts/twitter_web3">Twitter</a></td>
<td></td><td> {{twitter3}}</td></tr>
 -->


</table>


    {% else %}

        <h5><b>Welcome to the Spaced Database.</b></h5>

    {% endif %}

{% endblock %}

accounts/templates/accounts/log_in.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Log in' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Log in' %}</button>

    </form>

    <hr>



{% endblock %}

accounts/templates/accounts/log_out.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'You have sucessfully Logged out' %}</h4>

    <!--<p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>-->
    <br>
    <p>
        <a href="{% url 'accounts:log_in' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

accounts/templates/accounts/newpage.html
<html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<table class="table table-bordered">
  <thead>
    <tr>
     {% for heading in columns %}
      <th>{{ heading }} </th>
     {% endfor %}
  
    </tr>
  </thead>
  <tbody>
   {% for row in topic %}
    <tr>
    
      {% for col in row %}
        <td> {{ col }}</td>
      {% endfor %}
    </tr> 
  {% endfor %}
  </tbody>
</table>




    <!--Pagination-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if topic.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{ topic.previous_page_number }}">Previous</a>
          </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
        {% endif %}

        {% if topic.number|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ topic.number|add:'-5' }}">&hellip;</a></li>
        {% endif %}

        {% for i in topic.paginator.page_range %}
            {% if topic.number == i %}
                <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
            {% elif i > topic.number|add:'-5' and i < topic.number|add:'5' %}
                 <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if topic.paginator.num_pages > topic.number|add:'4' %}
           <li class="page-item"><a class="page-link" href="?page={{ topic.number|add:'5' }}">&hellip;</a></li>
        {% endif %}

        {% if topic.has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{ topic.next_page_number }}">Next</a>
          </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <!--end of Pagination-->


</html>

accounts/templates/accounts/search.html
<form method="get">
	<h1> Search Engine </h1>
	<input id='q' name='q' type='text' placeholder="Search..."  Size='50' />

</form>



{% for item in posts %}
	{{item}}
<br>
{% endfor %}



<!-- comment - ctl + /
uncomment - ctl + shift + / -->

accounts/templates/accounts/sign_up.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Create an account' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-success">{% trans 'Create' %}</button>

    </form>

{% endblock %}